title: Your Site Title
email: noah.dev@gmail.com
description: >- # This means to ignore newlines until "baseurl:"
  Write a short description of your site here.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://nchristopher.net/" # the base hostname & protocol for your site

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
  problems:
    output: true
  reading-blogs:
    output: true
  reading-books:
    output: true
  reading-papers:
    output: true
  # Add more collections as needed
